services:
  caddy:
    # image: caddy
    build: .
    container_name: caddy
    command: caddy run --config /etc/caddy/Caddyfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./static:/static:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tusd

  # https://tus.github.io/tusd/
  tusd:
    # image: tusproject/tusd
    build: .
    container_name: tusd
    command: tusd -upload-dir /data -behind-proxy -disable-download -port 8080
    volumes:
      - ./data:/data

  ldap:
    image: rroemhild/test-openldap
    container_name: ldap
