FROM golang:alpine AS builder
RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
RUN xcaddy build --with github.com/greenpau/caddy-security


FROM scratch
COPY --from=builder /go/caddy /usr/bin/caddy
ENTRYPOINT [ "/usr/bin/caddy" ]
