services:
  caddy:
    build:
      dockerfile: Dockerfile.caddy
    container_name: caddy
    command: run --config /etc/caddy/Caddyfile --watch
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./static:/static:ro
      - ./logs:/logs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tusd

  tusd:
    build:
      dockerfile: Dockerfile.tusd
    container_name: tusd
    command: -upload-dir /data -behind-proxy -disable-download -port 8080
    volumes:
      - ./data:/data

  ldap:
    image: rroemhild/test-openldap
    container_name: ldap
